apiVersion: v1
kind: Service
metadata:
  labels:
    app: testapp
  name: testapp
  annotations:
    metallb.universe.tf/address-pool: production
#  annotations:
  #  haproxy.org/check: "enabled"
  #  haproxy.org/forwarded-for: "enabled"
  #  haproxy.org/load-balance: "roundrobin"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: testapp
