apiVersion: v1
kind: Service
metadata:
  labels:
    app: hajobe
  name: hajobe
  annotations:
    metallb.universe.tf/address-pool: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: hajobe
