apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hajoui
  name: hajoui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hajoui
  template:
    metadata:
      labels:
        app: hajoui
    spec:
      containers:
      - name: hajoui
        image: lares/hajoui:latest
        ports:
          - name: http
            containerPort: 8080
