apiVersion: v1
kind: Service
metadata:
  labels:
    app: hajoui
  name: hajoui
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hajoui
